{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bookmarker.postgresql.pvcName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bookmarker.postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
