{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookmarker.fullname" $root }}-config
  namespace: {{ $root.Values.global.namespace }}
  labels:
    {{- include "bookmarker.labels" $root | nindent 4 }}
data:
  NODE_ENV: {{ $root.Values.config.nodeEnv | quote }}
  DATABASE_PROVIDER: {{ $root.Values.config.databaseProvider | quote }}
  PORT: {{ $root.Values.config.port | quote }}
  JWT_EXPIRES_IN: {{ $root.Values.config.jwtExpiresIn | quote }}
  REFRESH_TOKEN_EXPIRES_IN: {{ $root.Values.config.refreshTokenExpiresIn | quote }}
  NEXT_TELEMETRY_DISABLED: {{ $root.Values.config.nextTelemetryDisabled | quote }}
  {{- if $root.Values.config.corsOrigin }}
  CORS_ORIGIN: {{ $root.Values.config.corsOrigin | quote }}
  {{- end }}
