{{- if or .Values.secrets.jwtSecret .Values.secrets.dbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookmarker.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bookmarker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
