{{- $root := . -}}
{{- if $root.Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookmarker.backend.serviceName" $root }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
    {{- include "bookmarker.backend.labels" $root | nindent 4 }}
spec:
  type: {{ $root.Values.backend.service.type }}
  selector:
    {{- include "bookmarker.backend.selectorLabels" $root | nindent 4 }}
  ports:
  - port: {{ $root.Values.backend.service.port }}
    targetPort: {{ $root.Values.backend.service.targetPort }}
    protocol: TCP
{{- end }}
