{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookmarker.frontend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bookmarker.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bookmarker.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bookmarker.frontend.selectorLabels" . | nindent 8 }}
      {{- with .Values.frontend.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ include "bookmarker.fullname" . }}-config
              key: NODE_ENV
        - name: NEXT_TELEMETRY_DISABLED
          valueFrom:
            configMapKeyRef:
              name: {{ include "bookmarker.fullname" . }}-config
              key: NEXT_TELEMETRY_DISABLED
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "bookmarker.fullname" . }}-config
              key: NEXT_PUBLIC_API_URL
        livenessProbe:
          {{- toYaml .Values.frontend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.frontend.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
{{- end }}
